# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
# This file is YAML format.  By default the application is running in production mode, so you should just need
# change the "production" section of this file.  The application can be changed to run in development mode by editing
# the environment.rb configuration file in the "config" directory of the application, and then adding the appropriate
# database connection settings in this file under the "development" section.
# 
# An example configuration would be:
#
#production:
#  adapter: mysql
#  encoding: utf8
#  reconnect: false
#  database: username_dbname
#  pool: 5
#  username: username_mysqlusername
#  password: password
#  socket: /var/tmp/mysql.sock
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: 
  pool: 5
  username: 
  password: 
  socket: /tmp/mysql.sock

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: lembic_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: lembic_production
  pool: 5
  username: 
  password: 
  socket: /tmp/mysql.sock
